### ISSUE TITLE
Seems to break FXMaster.

### ISSUE THREAD

**Issue by huxoll** [relick/FoundryVTT-Right-Click-Enabler#1]
With this module enabled, the menu for FXMaster doesn't render; I only get the first 3 options (nothing after Snow).

Seems odd, but disabling the module gives me back the whole menu.

**Comment by relick** [comment]
I don't seem to be able to reproduce, using:
Foundry 0.7.9
FXMaster 1.0.3
Right Click Enabler 0.0.1

![image](https://user-images.githubusercontent.com/935382/118368232-dc904c00-b599-11eb-8afe-c9b67ad54453.png)

Are you able to verify with just these two modules yourself too? If it works, could you try and find out which other module might be interfering? If it doesn't work, could you tell me what system you are using?

**Comment by huxoll** [comment]
Interesting, it seems to be a collision of multiple modules.

If I have "Always Centred" enabled and "Right Click Enabler", the menu doesn't render.  If I turn either one off, I get the full collection of FXMaster.
https://foundryvtt.com/packages/always-centred/

It seems that there are multiple ways this can happen; it seems like the same thing happens with "Zoom/Pan Options" enabled, I have the same issue.
https://foundryvtt.com/packages/zoom-pan-options/

Maybe that helps?

**Comment by relick** [comment]
Thanks for responding. That helped a lot and I was able to identify the problem. If you update the module to 0.0.2, it should be fixed now!
