### ISSUE TITLE
[Compatibility Issue] Replacing 'Game' is not a good idea.

### ISSUE THREAD

**Issue by ruipin** [relick/FoundryVTT-Right-Click-Enabler#3]
Hello,

It has come to my attention that since 0.8.9 this module breaks `libWrapper`, as well as some modules that hook a function in `Game`. A quick investigation shows that this is caused by the fact that you replace the entirety of the `Game` class with a patched `toString()` version.

The problem here is that the `toString()` version of a method/class is not guaranteed to correspond to the actual code, especially if any method has been patched by another module. For example, variables that are from scopes outside the class (e.g. specific to a given method) will not be accessible. Methods might rely on native code and thus contain `[native]` blocks, etc. Using it for a single method is already an issue sometimes, but using it for an entire class - especially one modified by many modules - is a really bad idea if you want to have good compatibility with other modules.

In this case, libWrapper will patch `Game.prototype.initialize` to complete its initialisation, but this patch is thrown out when you replace the `Game` class, causing libWrapper to never fully initialise. This used to work before 0.8.9 as libWrapper would load after your module, but in 0.8.9 the module loading order changed, and now your module loads after.

Some other modules that patch `Game` also lose their patches and stop working correctly, but neither fails as obviously as libWrapper.

Given you want to remove the line `document.addEventListener("contextmenu", ev => ev.preventDefault());` in method `Game.prototype.activateListeners`, you could achieve the exact same result without being a nightmare for module compatibility, by restricting your patch to the `activateListeners` method itself, e.g.:

````js
const fnStr = Game.prototype.activateListeners.toString();
const patchedFnStr = fnStr .replace(`document.addEventListener("contextmenu", ev => ev.preventDefault());`, ``);
Game.prototype.activateListeners = Function('"use strict"; return (function ' + patchedFnStr + ')')();
````

**Comment by relick** [comment]
Thank you for the thorough bug report. I was under the mistaken impression that toString would reflect the code of the class. I have fixed it in 0.0.3.
